apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack-deployment
spec:
  selector:
    matchLabels:
      app: localstack
  replicas: 1
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:1.4
          ports:
            - containerPort: 4566
              name: edge
            - containerPort: 4510
              name: opensearch
          resources:
            limits:
              cpu: 2000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 500Mi
          livenessProbe:
            httpGet:
              path: /_localstack/health
              port: edge
          readinessProbe:
            httpGet:
              path: /_localstack/health
              port: edge
          env:
            - name: SERVICES
              value: s3,opensearch
            - name: OPENSEARCH_ENDPOINT_STRATEGY
              value: port
          volumeMounts:
            - name: localstack-init-script
              mountPath: /docker-entrypoint-initaws.d/
      volumes:
        - name: localstack-init-script
          configMap:
            name: localstack-init-script
