apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  ports:
    - name: edge
      port: 4566
      targetPort: edge
    - name: opensearch
      port: 4510
      targetPort: opensearch
  selector:
    app: localstack
