on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: little-core-labs/get-git-tag@v3.0.1 # https://github.com/olegtarasov/get-tag/issues/14
        id: tagName
        with:
          tagRegex: "v(.*)"
          tagRegexGroup: 1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Assemble assets
        run: |
          sbt "++ 2.12.10" assembly

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.tagName.outputs.tag }}
          draft: true
          prerelease: false
          body_path: CHANGELOG.md
          files: |
            target/scala-2.12/snapshot-streaming-assembly-${{ steps.tagName.outputs.tag }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
