name: Deploy

inputs:
  SSH_NODE_HOST:
    required: true
  SSH_NODE_USER:
    required: true
  SSH_PRIVATE_KEY:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ inputs.SSH_PRIVATE_KEY }}

    - name: Download JAR artifacts
      uses: actions/download-artifact@v4
      with:
        name: jar-files
        path: ./jar-files

    - name: Copy JARs to all nodes
      shell: bash
      run: |
        # Copy snapshot-streaming.jar
        scp -o StrictHostKeyChecking=no jar-files/snapshot-streaming.jar ${{ inputs.SSH_NODE_USER }}@${{ inputs.SSH_NODE_HOST }}:snapshot-streaming/snapshot-streaming.jar

    - name: Restart snapshot streaming service
      shell: bash
      run: |
        ssh -o StrictHostKeyChecking=no ${{ inputs.SSH_NODE_USER }}@${{ inputs.SSH_NODE_HOST }} "cd snapshot-streaming; ./restart"