on: pull_request

name: Pull request tests.

jobs:
  test:
    name: Pull request tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: snapshot-streaming

      - name: Checkout tessellation
        uses: actions/checkout@v3
        with:
          path: tessellation
          repository: Constellation-Labs/tessellation
          ref: v2.0.0-alpha.2
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: sbt

      - name: Build tessellation packages
        run: (cd tessellation; sbt kernel/publishM2 shared/publishM2 keytool/publishM2 sdk/publishM2)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile
        run: (cd snapshot-streaming; sbt test)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

