on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: snapshot-streaming

      - name: Checkout tessellation
        uses: actions/checkout@v3
        with:
          path: tessellation
          repository: Constellation-Labs/tessellation
          ref: v1.9.1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: sbt

      - name: Build tessellation packages
        run: (cd tessellation; sbt kernel/publishM2 shared/publishM2 keytool/publishM2 sdk/publishM2 dagShared/publishM2)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Assembly
        run: (cd snapshot-streaming; sbt assembly)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: true
          prerelease: false
          body_path: snapshot-streaming/CHANGELOG.md
          files: snapshot-streaming/target/scala-2.13/snapshot-streaming-assembly-${RELEASE_VERSION#v}.jar
        env:
          RELEASE_VERSION: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}