#!/bin/sh
#ulimit -c unlimited
#ulimit -n 60036
java "-Dcom.sun.management.jmxremote" \
"-Dcom.sun.management.jmxremote.port=9011" \
"-Dcom.sun.management.jmxremote.rmi.port=9011" \
"-Dcom.sun.management.jmxremote.local.only=false" \
"-Dcom.sun.management.jmxremote.authenticate=false" \
"-Dcom.sun.management.jmxremote.ssl=false" \
"-Djava.rmi.server.hostname=127.0.0.1" \
"-Dconfig.file=/home/ec2-user/snapshot-streaming/application.conf" \
"-Dlogback.configurationFile=/home/ec2-user/snapshot-streaming/logback.xml" \
"-XX:+HeapDumpOnOutOfMemoryError" \
"-Xms1024M" \
"-Xmx3G" \
"-Xss256K" \
-jar snapshot-streaming.jar